-- Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient_id TEXT NULL,
  recipient_role TEXT NULL,
  recipient_email TEXT NULL,
  recipient_name TEXT NULL,
  work_order_no TEXT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'work_order_created',
  created_by TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  read_at TIMESTAMP WITH TIME ZONE NULL,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_id, recipient_role);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_read_at ON notifications(read_at);
